version: '3'

services:
  bot:
    build: .
    restart: always
    container_name: bot
    command: python run.py
    volumes:
      - .:/revda_ekb_bus_bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
